import { Train, Disruption, Booking, AlertItem, RouteSection, ModelMetrics, PredictionHistoryRecord, AuditLogItem } from '../types/railway';

export const CORRIDOR_SECTIONS: RouteSection[] = [
  {
    id: 'SEC_MAS_AJJ',
    fromCode: 'MAS',
    toCode: 'AJJ',
    fromName: 'Chennai Central',
    toName: 'Arakkonam Jn',
    distanceKm: 69,
    normalRuntimeMin: 55,
    currentSpeedKmH: 82,
    maxSpeedKmH: 110,
    congestionLevel: 'NORMAL',
    signalStatus: 'CLEAR',
    weatherFactor: 'CLEAR',
    recoveryBufferMin: 3
  },
  {
    id: 'SEC_AJJ_KPD',
    fromCode: 'AJJ',
    toCode: 'KPD',
    fromName: 'Arakkonam Jn',
    toName: 'Katpadi Jn',
    distanceKm: 61,
    normalRuntimeMin: 48,
    currentSpeedKmH: 54,
    maxSpeedKmH: 110,
    congestionLevel: 'HIGH',
    signalStatus: 'RESTRICTED',
    weatherFactor: 'RAIN',
    recoveryBufferMin: 2,
    speedRestrictionKmH: 60
  },
  {
    id: 'SEC_KPD_JTJ',
    fromCode: 'KPD',
    toCode: 'JTJ',
    fromName: 'Katpadi Jn',
    toName: 'Jolarpettai Jn',
    distanceKm: 84,
    normalRuntimeMin: 65,
    currentSpeedKmH: 95,
    maxSpeedKmH: 110,
    congestionLevel: 'NORMAL',
    signalStatus: 'CLEAR',
    weatherFactor: 'CLEAR',
    recoveryBufferMin: 4
  },
  {
    id: 'SEC_JTJ_KJM',
    fromCode: 'JTJ',
    toCode: 'KJM',
    fromName: 'Jolarpettai Jn',
    toName: 'Krishnarajapuram',
    distanceKm: 128,
    normalRuntimeMin: 98,
    currentSpeedKmH: 102,
    maxSpeedKmH: 130,
    congestionLevel: 'LOW',
    signalStatus: 'CLEAR',
    weatherFactor: 'CLEAR',
    recoveryBufferMin: 5
  },
  {
    id: 'SEC_KJM_SBC',
    fromCode: 'KJM',
    toCode: 'SBC',
    fromName: 'Krishnarajapuram',
    toName: 'KSR Bengaluru',
    distanceKm: 14,
    normalRuntimeMin: 24,
    currentSpeedKmH: 45,
    maxSpeedKmH: 75,
    congestionLevel: 'MODERATE',
    signalStatus: 'CAUTION',
    weatherFactor: 'CLEAR',
    recoveryBufferMin: 1
  }
];

export const INITIAL_TRAINS: Train[] = [
  {
    id: '12627',
    number: '12627',
    name: 'Karnataka Express',
    type: 'SUPERFAST',
    origin: 'Chennai Central',
    originCode: 'MAS',
    destination: 'KSR Bengaluru',
    destinationCode: 'SBC',
    currentStation: 'Katpadi Jn Approach',
    currentStationCode: 'KPD',
    nextStation: 'Katpadi Jn',
    nextStationCode: 'KPD',
    progressKm: 122,
    totalKm: 356,
    currentSpeedKmH: 58,
    status: 'RUNNING',
    scheduledDeparture: '6:15 PM',
    scheduledArrival: '8:20 PM',
    currentDelayMin: 10,
    predictedDelayMin: 9,
    predictedArrival: '8:29 PM',
    confidence: 87,
    bestCaseArrival: '8:24 PM',
    worstCaseArrival: '8:36 PM',
    probDelayExceeds5Min: 74,
    probDelayExceeds10Min: 22,
    expectedRecoveryMin: 4,
    platform: 5,
    primaryCause: 'Signal congestion approaching Platform 5 at Katpadi Jn',
    coordinates: { x: 34, y: 48 },
    stops: [
      {
        stationCode: 'MAS',
        stationName: 'Chennai Central',
        km: 0,
        scheduledArrival: '06:00 PM',
        scheduledDeparture: '06:15 PM',
        predictedArrival: '06:00 PM',
        predictedDeparture: '06:15 PM',
        delayMin: 0,
        platform: 4,
        confidence: 99,
        status: 'DEPARTED',
        crowdDensity: 82
      },
      {
        stationCode: 'AJJ',
        stationName: 'Arakkonam Jn',
        km: 69,
        scheduledArrival: '06:58 PM',
        scheduledDeparture: '07:00 PM',
        predictedArrival: '07:01 PM',
        predictedDeparture: '07:03 PM',
        delayMin: 3,
        platform: 2,
        confidence: 94,
        status: 'DEPARTED',
        crowdDensity: 64
      },
      {
        stationCode: 'KPD',
        stationName: 'Katpadi Jn',
        km: 130,
        scheduledArrival: '07:42 PM',
        scheduledDeparture: '07:44 PM',
        predictedArrival: '07:51 PM',
        predictedDeparture: '07:53 PM',
        delayMin: 9,
        platform: 5,
        confidence: 86,
        status: 'UPCOMING',
        crowdDensity: 78,
        platformConflictRisk: 'MEDIUM',
        alternativePlatform: 6
      },
      {
        stationCode: 'JTJ',
        stationName: 'Jolarpettai Jn',
        km: 214,
        scheduledArrival: '08:05 PM',
        scheduledDeparture: '08:07 PM',
        predictedArrival: '08:12 PM',
        predictedDeparture: '08:14 PM',
        delayMin: 7,
        platform: 3,
        confidence: 88,
        status: 'UPCOMING',
        crowdDensity: 52
      },
      {
        stationCode: 'KJM',
        stationName: 'Krishnarajapuram',
        km: 342,
        scheduledArrival: '08:48 PM',
        scheduledDeparture: '08:50 PM',
        predictedArrival: '08:53 PM',
        predictedDeparture: '08:55 PM',
        delayMin: 5,
        platform: 4,
        confidence: 89,
        status: 'UPCOMING',
        crowdDensity: 74
      },
      {
        stationCode: 'SBC',
        stationName: 'KSR Bengaluru',
        km: 356,
        scheduledArrival: '08:20 PM',
        scheduledDeparture: '08:20 PM',
        predictedArrival: '08:29 PM',
        predictedDeparture: '08:29 PM',
        delayMin: 9,
        platform: 5,
        confidence: 87,
        status: 'UPCOMING',
        crowdDensity: 88,
        platformConflictRisk: 'MEDIUM',
        alternativePlatform: 6
      }
    ],
    whyETAChanged: [
      { category: 'Signaling', name: 'Signal congestion at Katpadi approach', delayMin: 5, percentage: 45 },
      { category: 'Headway', name: 'Preceding local train headway clearance', delayMin: 3, percentage: 27 },
      { category: 'Station Dwell', name: 'Extended passenger boarding at Arakkonam', delayMin: 2, percentage: 18 },
      { category: 'Weather', name: 'Intermittent rain & wet rail adhesion', delayMin: 1, percentage: 10 }
    ],
    recoveryBreakdown: [
      { sectionName: 'AJJ → KPD', recoveryMin: 0, sectionDistanceKm: 61, speedHeadroomKmH: 0 },
      { sectionName: 'KPD → JTJ', recoveryMin: -2, sectionDistanceKm: 84, speedHeadroomKmH: 15 },
      { sectionName: 'JTJ → KJM (High Speed Quad)', recoveryMin: -3, sectionDistanceKm: 128, speedHeadroomKmH: 28 },
      { sectionName: 'KJM → SBC', recoveryMin: 1, sectionDistanceKm: 14, speedHeadroomKmH: 0 }
    ],
    evolution: [
      { timeLabel: '6:15 PM', minutesAgo: 75, predictedDelayMin: 0, confidence: 96, eventNote: 'On-time departure from MAS' },
      { timeLabel: '6:45 PM', minutesAgo: 45, predictedDelayMin: 2, confidence: 93, eventNote: 'Slow clearance at Tiruvallur' },
      { timeLabel: '7:05 PM', minutesAgo: 25, predictedDelayMin: 4, confidence: 90, eventNote: 'Departed AJJ +3 min' },
      { timeLabel: '7:20 PM', minutesAgo: 10, predictedDelayMin: 8, confidence: 85, eventNote: 'Signal stop outside Mukundarayapuram' },
      { timeLabel: 'Now (7:30 PM)', minutesAgo: 0, predictedDelayMin: 9, confidence: 87, eventNote: 'AI factoring downstream speed recovery' }
    ],
    downstreamAffectedTrains: ['12028', '16528', '12678'],
    passengerConnectionRisksCount: 8
  },
  {
    id: '12028',
    number: '12028',
    name: 'Shatabdi Express',
    type: 'SHATABDI',
    origin: 'KSR Bengaluru',
    originCode: 'SBC',
    destination: 'Chennai Central',
    destinationCode: 'MAS',
    currentStation: 'Arakkonam Jn',
    currentStationCode: 'AJJ',
    nextStation: 'Chennai Central',
    nextStationCode: 'MAS',
    progressKm: 287,
    totalKm: 356,
    currentSpeedKmH: 94,
    status: 'RUNNING',
    scheduledDeparture: '04:15 PM',
    scheduledArrival: '08:35 PM',
    currentDelayMin: 4,
    predictedDelayMin: 3,
    predictedArrival: '08:38 PM',
    confidence: 93,
    bestCaseArrival: '08:35 PM',
    worstCaseArrival: '08:42 PM',
    probDelayExceeds5Min: 28,
    probDelayExceeds10Min: 6,
    expectedRecoveryMin: 2,
    platform: 2,
    primaryCause: 'Speed restriction near Perambur carriage works',
    coordinates: { x: 78, y: 38 },
    stops: [],
    whyETAChanged: [
      { category: 'Permanent Way', name: 'Speed restriction (60 km/h) Perambur', delayMin: 3, percentage: 65 },
      { category: 'Signaling', name: 'Platform 2 routing at MAS', delayMin: 1, percentage: 35 }
    ],
    recoveryBreakdown: [
      { sectionName: 'AJJ → MAS', recoveryMin: -1, sectionDistanceKm: 69, speedHeadroomKmH: 18 }
    ],
    evolution: [
      { timeLabel: '7:00 PM', minutesAgo: 30, predictedDelayMin: 5, confidence: 91 },
      { timeLabel: 'Now', minutesAgo: 0, predictedDelayMin: 3, confidence: 93 }
    ],
    downstreamAffectedTrains: ['22691'],
    passengerConnectionRisksCount: 2
  },
  {
    id: '16528',
    number: '16528',
    name: 'Kannur - Yesvantpur Express',
    type: 'EXPRESS',
    origin: 'Kannur',
    originCode: 'CAN',
    destination: 'Yesvantpur Jn',
    destinationCode: 'YPR',
    currentStation: 'Jolarpettai Jn',
    currentStationCode: 'JTJ',
    nextStation: 'Bangarapet Jn',
    nextStationCode: 'BWT',
    progressKm: 220,
    totalKm: 420,
    currentSpeedKmH: 68,
    status: 'RUNNING',
    scheduledDeparture: '05:00 PM',
    scheduledArrival: '08:45 PM',
    currentDelayMin: 7,
    predictedDelayMin: 5,
    predictedArrival: '08:50 PM',
    confidence: 89,
    bestCaseArrival: '08:47 PM',
    worstCaseArrival: '08:55 PM',
    probDelayExceeds5Min: 48,
    probDelayExceeds10Min: 12,
    expectedRecoveryMin: 3,
    platform: 3,
    primaryCause: 'Preceding freight rake precedence near Kuppam ghats',
    coordinates: { x: 48, y: 64 },
    stops: [],
    whyETAChanged: [
      { category: 'Congestion', name: 'Ghat section loop precedence', delayMin: 5, percentage: 70 },
      { category: 'Weather', name: 'Fog in Kuppam valley', delayMin: 2, percentage: 30 }
    ],
    recoveryBreakdown: [
      { sectionName: 'JTJ → BWT', recoveryMin: -2, sectionDistanceKm: 70, speedHeadroomKmH: 15 }
    ],
    evolution: [
      { timeLabel: '6:30 PM', minutesAgo: 60, predictedDelayMin: 8, confidence: 84 },
      { timeLabel: 'Now', minutesAgo: 0, predictedDelayMin: 5, confidence: 89 }
    ],
    downstreamAffectedTrains: ['12678'],
    passengerConnectionRisksCount: 5
  },
  {
    id: '12678',
    number: '12678',
    name: 'Ernakulam - Bengaluru Intercity',
    type: 'INTERCITY',
    origin: 'Ernakulam Jn',
    originCode: 'ERS',
    destination: 'KSR Bengaluru',
    destinationCode: 'SBC',
    currentStation: 'Hosur Approach',
    currentStationCode: 'HSRA',
    nextStation: 'Karmelaram',
    nextStationCode: 'CRLM',
    progressKm: 310,
    totalKm: 380,
    currentSpeedKmH: 74,
    status: 'DELAYED',
    scheduledDeparture: '09:10 AM',
    scheduledArrival: '07:50 PM',
    currentDelayMin: 18,
    predictedDelayMin: 14,
    predictedArrival: '08:04 PM',
    confidence: 84,
    bestCaseArrival: '08:01 PM',
    worstCaseArrival: '08:12 PM',
    probDelayExceeds5Min: 92,
    probDelayExceeds10Min: 68,
    expectedRecoveryMin: 4,
    platform: 7,
    primaryCause: 'Interlocking point failure at Dharmapuri Jn',
    coordinates: { x: 72, y: 76 },
    stops: [],
    whyETAChanged: [
      { category: 'Interlocking', name: 'Point failure Dharmapuri', delayMin: 12, percentage: 67 },
      { category: 'Speed Restriction', name: 'Single line caution order', delayMin: 6, percentage: 33 }
    ],
    recoveryBreakdown: [
      { sectionName: 'HSRA → SBC', recoveryMin: -4, sectionDistanceKm: 50, speedHeadroomKmH: 20 }
    ],
    evolution: [
      { timeLabel: '6:00 PM', minutesAgo: 90, predictedDelayMin: 22, confidence: 79 },
      { timeLabel: 'Now', minutesAgo: 0, predictedDelayMin: 14, confidence: 84 }
    ],
    downstreamAffectedTrains: [],
    passengerConnectionRisksCount: 14
  },
  {
    id: '22691',
    number: '22691',
    name: 'KSR Bengaluru Rajdhani Express',
    type: 'RAJDHANI',
    origin: 'Hazrat Nizamuddin',
    originCode: 'NZM',
    destination: 'KSR Bengaluru',
    destinationCode: 'SBC',
    currentStation: 'Dharmavaram Jn',
    currentStationCode: 'DMM',
    nextStation: 'Yelahanka Jn',
    nextStationCode: 'YNK',
    progressKm: 2150,
    totalKm: 2365,
    currentSpeedKmH: 112,
    status: 'ON_TIME',
    scheduledDeparture: '08:00 PM',
    scheduledArrival: '06:40 AM',
    currentDelayMin: 0,
    predictedDelayMin: 0,
    predictedArrival: '06:40 AM',
    confidence: 96,
    bestCaseArrival: '06:36 AM',
    worstCaseArrival: '06:45 AM',
    probDelayExceeds5Min: 8,
    probDelayExceeds10Min: 2,
    expectedRecoveryMin: 6,
    platform: 1,
    primaryCause: 'On-schedule high-priority track allocation',
    coordinates: { x: 22, y: 22 },
    stops: [],
    whyETAChanged: [],
    recoveryBreakdown: [],
    evolution: [],
    downstreamAffectedTrains: [],
    passengerConnectionRisksCount: 0
  },
  {
    id: '12296',
    number: '12296',
    name: 'Sanghamitra Superfast Express',
    type: 'SUPERFAST',
    origin: 'Danapur',
    originCode: 'DNR',
    destination: 'KSR Bengaluru',
    destinationCode: 'SBC',
    currentStation: 'Gudiyattam',
    currentStationCode: 'GYM',
    nextStation: 'Katpadi Jn',
    nextStationCode: 'KPD',
    progressKm: 145,
    totalKm: 2690,
    currentSpeedKmH: 62,
    status: 'RUNNING',
    scheduledDeparture: '08:10 PM',
    scheduledArrival: '08:20 PM',
    currentDelayMin: 8,
    predictedDelayMin: 7,
    predictedArrival: '08:27 PM',
    confidence: 88,
    bestCaseArrival: '08:23 PM',
    worstCaseArrival: '08:33 PM',
    probDelayExceeds5Min: 62,
    probDelayExceeds10Min: 18,
    expectedRecoveryMin: 3,
    platform: 4,
    primaryCause: 'Caution order on Palar river bridge',
    coordinates: { x: 38, y: 52 },
    stops: [],
    whyETAChanged: [],
    recoveryBreakdown: [],
    evolution: [],
    downstreamAffectedTrains: ['12627'],
    passengerConnectionRisksCount: 6
  }
];

export const INITIAL_DISRUPTIONS: Disruption[] = [
  {
    id: 'DISR_01',
    type: 'SIGNAL_CONGESTION',
    title: 'Signal Interlock Congestion',
    location: 'Katpadi Junction (KPD) North Approach',
    stationCode: 'KPD',
    severity: 'HIGH',
    impactMin: 10,
    affectedTrainNumbers: ['12627', '12296', '16528'],
    description: 'Auto-signaling block 42 experiencing track circuit fluctuations. Speeds reduced to 15 km/h on approach to Platform 5.',
    timestamp: '7:24 PM',
    source: 'LIVE DATA',
    isActive: true
  },
  {
    id: 'DISR_02',
    type: 'PLATFORM_CONFLICT',
    title: 'Platform 5 Overlap Risk',
    location: 'KSR Bengaluru (SBC)',
    stationCode: 'SBC',
    severity: 'MEDIUM',
    impactMin: 6,
    affectedTrainNumbers: ['12627', '12028'],
    description: 'Train 12627 delayed arrival overlaps with Train 12028 rake maintenance turnaround slot on Platform 5.',
    timestamp: '7:28 PM',
    source: 'AI PREDICTION',
    isActive: true
  },
  {
    id: 'DISR_03',
    type: 'WEATHER',
    title: 'Localized Heavy Rain & Adhesion Warning',
    location: 'Arakkonam - Mukundarayapuram Stretch',
    stationCode: 'AJJ',
    severity: 'LOW',
    impactMin: 3,
    affectedTrainNumbers: ['12627'],
    description: 'Monsoon downpour causing wheel-slip warning on locomotive WAP-7 30452. Traction braking buffer adjusted.',
    timestamp: '7:15 PM',
    source: 'LIVE DATA',
    isActive: true
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'BKG_99214',
    pnr: '428-9102845',
    trainNumber: '12627',
    trainName: 'Karnataka Express',
    from: 'Chennai Central (MAS)',
    to: 'KSR Bengaluru (SBC)',
    date: '05 Sep 2026',
    seatClass: '3A',
    coach: 'B4',
    berth: '32 (Side Lower)',
    status: 'CONFIRMED',
    passengerName: 'Aayush Sharma',
    fare: 765,
    scheduledArrival: '8:20 PM',
    predictedArrival: '8:29 PM'
  }
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'ALT_01',
    type: 'ETA_CHANGED',
    title: 'ETA Updated (+9 min)',
    message: 'Your train 12627 is now predicted to arrive at KSR Bengaluru at 8:29 PM (earlier 8:20 PM) due to signal congestion approaching Katpadi.',
    timeAgo: '2 min ago',
    severity: 'WARNING',
    trainNumber: '12627'
  },
  {
    id: 'ALT_02',
    type: 'CONNECTION_RISK',
    title: 'Connecting Train Advisory',
    message: 'Your transfer to Train 16216 Chamundi Express (Dep 8:45 PM SBC) has 16 min buffer. Connection probability: 82% (Safe).',
    timeAgo: '14 min ago',
    severity: 'INFO',
    trainNumber: '12627'
  },
  {
    id: 'ALT_03',
    type: 'PLATFORM_CHANGE',
    title: 'Platform Confirmation',
    message: 'Confirmed on Platform 5 at Katpadi Jn. Stand by coach indicator B4.',
    timeAgo: '28 min ago',
    severity: 'INFO',
    trainNumber: '12627'
  }
];

export const FEATURE_IMPORTANCE = [
  { feature: 'Historical Running Time on Section', weight: 0.28, description: 'Long-term rolling average travel duration by train class and rake type' },
  { feature: 'Current Section Speed vs Limit', weight: 0.22, description: 'GPS & speedometer telemetry divergence from section maximum permissible speed' },
  { feature: 'Signal Interlock Congestion Index', weight: 0.18, description: 'Occupancy duration of route track circuits and signal caution states' },
  { feature: 'Preceding Train Headway Gap', weight: 0.14, description: 'Distance and time separation from the preceding rake in the same block' },
  { feature: 'Station Scheduled Dwell Buffer', weight: 0.10, description: 'Slack scheduled in passenger halt vs observed boarding time' },
  { feature: 'Weather & Rail Adhesion Factor', weight: 0.05, description: 'Precipitation, ambient temperature, fog visibility, and rail friction' },
  { feature: 'Time of Day / Peak Corridor Load', weight: 0.03, description: 'Suburban commuter peak intersection and junction crossing conflicts' }
];

export const MODEL_VERSIONS = [
  {
    version: 'v1.4',
    name: 'RailSync XGBoost/LightGBM Ensemble',
    status: 'ACTIVE',
    mae: 8.7,
    rmse: 12.4,
    coverage: 94.2,
    confidence: 87.4,
    deployedDate: '01 Sep 2026',
    notes: 'Incorporated dynamic downstream recovery buffers and high-speed quad track section models.'
  },
  {
    version: 'v1.3',
    name: 'Gradient Boosting Regressor',
    status: 'ARCHIVED',
    mae: 10.4,
    rmse: 14.8,
    coverage: 91.0,
    confidence: 83.1,
    deployedDate: '15 Aug 2026',
    notes: 'Previous stable release. Lacked explicit wheel-adhesion weather weighting.'
  },
  {
    version: 'v1.2',
    name: 'Statistical Moving Average + NTES Delay Offset',
    status: 'ARCHIVED',
    mae: 14.2,
    rmse: 19.4,
    coverage: 88.5,
    confidence: 76.0,
    deployedDate: '01 Jul 2026',
    notes: 'Baseline statistical tracker without section-level dynamic feature engineering.'
  }
];

export const INITIAL_PREDICTION_HISTORY: PredictionHistoryRecord[] = [
  {
    id: 'PRD_8091',
    timestamp: '07:29:42 PM',
    trainNumber: '12627',
    stationCode: 'SBC',
    scheduledETA: '08:20 PM',
    predictedETA: '08:29 PM',
    actualETA: 'Pending (In Transit)',
    errorMin: 0.8,
    confidence: 87,
    modelVersion: 'v1.4',
    primaryFactor: 'Signal congestion at Katpadi'
  },
  {
    id: 'PRD_8090',
    timestamp: '07:14:10 PM',
    trainNumber: '12028',
    stationCode: 'MAS',
    scheduledETA: '08:35 PM',
    predictedETA: '08:38 PM',
    actualETA: '08:37 PM',
    errorMin: 1.0,
    confidence: 93,
    modelVersion: 'v1.4',
    primaryFactor: 'Speed restriction near Perambur'
  },
  {
    id: 'PRD_8089',
    timestamp: '06:58:33 PM',
    trainNumber: '16528',
    stationCode: 'SBC',
    scheduledETA: '08:45 PM',
    predictedETA: '08:50 PM',
    actualETA: 'Pending',
    errorMin: 1.4,
    confidence: 89,
    modelVersion: 'v1.4',
    primaryFactor: 'Ghat precedence Kuppam'
  },
  {
    id: 'PRD_8088',
    timestamp: '06:40:15 PM',
    trainNumber: '12678',
    stationCode: 'SBC',
    scheduledETA: '07:50 PM',
    predictedETA: '08:04 PM',
    actualETA: '08:06 PM',
    errorMin: 2.0,
    confidence: 84,
    modelVersion: 'v1.4',
    primaryFactor: 'Interlocking point failure Dharmapuri'
  },
  {
    id: 'PRD_8087',
    timestamp: '06:15:00 PM',
    trainNumber: '22691',
    stationCode: 'SBC',
    scheduledETA: '06:40 AM',
    predictedETA: '06:40 AM',
    actualETA: 'Pending',
    errorMin: 0.2,
    confidence: 96,
    modelVersion: 'v1.4',
    primaryFactor: 'Nominal High Speed Schedule'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'LOG_104',
    timestamp: '07:25:12 PM',
    userRole: 'admin',
    action: 'ETA Model Parameter Update',
    resource: 'v1.4 Rake Recovery Coefficient',
    result: 'SUCCESS',
    details: 'Calibrated downhill gradient acceleration between Jolarpettai and Bangarapet.'
  },
  {
    id: 'LOG_103',
    timestamp: '07:22:45 PM',
    userRole: 'control_room',
    action: 'What-If Simulation Executed',
    resource: 'Scenario #42 (Katpadi +10 min Stoppage)',
    result: 'SUCCESS',
    details: 'Cascading impact assessed for 6 downstream rakes.'
  },
  {
    id: 'LOG_102',
    timestamp: '07:18:30 PM',
    userRole: 'station_staff',
    action: 'Platform Conflict Flagged',
    resource: 'SBC Platform 5',
    result: 'WARNING',
    details: 'AI alert generated for 12627 and 12028 overlap.'
  },
  {
    id: 'LOG_101',
    timestamp: '07:05:00 PM',
    userRole: 'admin',
    action: 'Data Stream Ingestion Health Check',
    resource: 'GPS & NTES Feeds',
    result: 'SUCCESS',
    details: 'Latency under 45ms across 1,248 active coaching trains.'
  }
];
